/* ################################ AUTH ####################### */
export const LOGIN = 'LOGIN'
export const LOGIN_RECEIVED = 'LOGIN_RECEIVED'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const LOGOUT = 'LOGOUT'
export const LOGOUT_RECEIVED = 'LOGOUT_RECEIVED'
export const LOGOUT_FAILED = 'LOGOUT_FAILED'

export const RESET_PASSWORD = 'RESET_PASSWORD'
export const RESET_PASSWORD_RECEIVED = 'RESET_PASSWORD_RECEIVED'
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED'

export const REGISTER = 'REGISTER'
export const REGISTER_RECEIVED = 'REGISTER_RECEIVED'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const REGISTER_FACEBOOK = 'REGISTER_FACEBOOK'
export const REGISTER_FACEBOOK_RECEIVED = 'REGISTER_FACEBOOK_RECEIVED'
export const REGISTER_FACEBOOK_FAILED = 'REGISTER_FACEBOOK_FAILED'

export const CLEAR_REGISTER = 'CLEAR_REGISTER'

export const RECOVER_PASSWORD = 'RECOVER_PASSWORD'
export const RECOVER_PASSWORD_RECEIVED = 'RECOVER_PASSWORD_RECEIVED'
export const RECOVER_PASSWORD_FAILED = 'RECOVER_PASSWORD_FAILED'

export const VERIFY_CODE = 'VERIFY_CODE';
export const VERIFY_CODE_RECEIVED = 'VERIFY_CODE_RECEIVED';
export const VERIFY_CODE_FAILED = 'VERIFY_CODE_FAILED';

/* ################################ FIN AUTH ####################### */

/* ############################### USER ####################### */
export const GET_USER_BY_NAME = 'GET_USER_BY_NAME';
export const GET_USER_BY_NAME_RECEIVED = 'GET_USER_BY_NAME_RECEIVED';
export const GET_USER_BY_NAME_FAILED = 'GET_USER_BY_NAME_FAILED';

export const GET_USER_BY_ID = 'GET_USER_BY_ID';
export const GET_USER_BY_ID_RECEIVED = 'GET_USER_BY_ID_RECEIVED';
export const GET_USER_BY_ID_FAILED = 'GET_USER_BY_ID_FAILED';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_RECEIVED = 'UPDATE_PROFILE_RECEIVED';
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED';

export const GET_USER_BY_USERNAME = 'GET_USER_BY_USERNAME';
export const GET_USER_BY_USERNAME_RECEIVED = 'GET_USER_BY_USERNAME_RECEIVED';
export const GET_USER_BY_USERNAME_FAILED = 'GET_USER_BY_USERNAME_FAILED';


/* ############################# END USERS ################### */

/* ######################### FORO ############################## */
export const FORO_POST_CREATE = 'FORO_POST_CREATE'
export const FORO_POST_CREATE_RECEIVED = 'FORO_POST_CREATE_RECEIVED'
export const FORO_POST_CREATE_FAILED = 'FORO_POST_CREATE_FAILED'

export const SET_IMAGE_FORO = 'SET_IMAGE_FORO'

export const CLEAR_POST = 'CLEAR_POST'

export const FORO_POST_GET = 'FORO_POST_GET'
export const FORO_POST_GET_RECEIVED = 'FORO_POST_GET_RECEIVED'
export const FORO_POST_GET_FAILED = 'FORO_POST_GET_FAILED'

export const UPDATE_POINT_GET = 'UPDATE_POINT_GET'
export const UPDATE_POINT_GET_RECEIVED = 'UPDATE_POINT_GET_RECEIVED'
export const UPDATE_POINT_GET_FAILED = 'UPDATE_POINT_GET_FAILED'

export const SET_COMMENT = 'SET_COMMENT'
export const SET_COMMENT_RECEIVED = 'SET_COMMENT_RECEIVED'
export const SET_COMMENT_FAILED = 'SET_COMMENT_FAILED'

export const GET_COMMENTS_BY_POST = 'GET_COMMENTS_BY_POST'
export const GET_COMMENTS_BY_POST_RECEIVED = 'GET_COMMENTS_BY_POST_RECEIVED'
export const GET_COMMENTS_BY_POST_FAILED = 'GET_COMMENTS_BY_POST_FAILED'

export const DELETE_COMMENT_POST = 'DELETE_COMMENT_POST'
export const DELETE_COMMENT_POST_RECEIVED = 'DELETE_COMMENT_POST_RECEIVED'
export const DELETE_COMMENT_POST_FAILED = 'DELETE_COMMENT_POST_FAILED'

export const CLEAR_DEL_COMMENT = 'CLEAR_DEL_COMMENT'

export const SET_FOLLOW = 'SET_FOLLOW'
export const SET_FOLLOW_RECEIVED = 'SET_FOLLOW_RECEIVED'
export const SET_FOLLOW_FAILED = 'SET_FOLLOW_FAILED'

export const FORO_POST_BY_ID_GET = 'FORO_POST_BY_ID_GET'
export const FORO_POST_BY_ID_GET_RECEIVED = 'FORO_POST_BY_ID_GET_RECEIVED'
export const FORO_POST_BY_ID_GET_FAILED = 'FORO_POST_BY_ID_GET_FAILED'

export const FORO_GET_FOLLOWS = 'FORO_GET_FOLLOWS'
export const FORO_GET_FOLLOWS_RECEIVED = 'FORO_GET_FOLLOWS_RECEIVED'
export const FORO_GET_FOLLOWS_FAILED = 'FORO_GET_FOLLOWS_FAILED'

export const SET_TYPE_FOLLOW = 'SET_TYPE_FOLLOW'

export const DELETE_FOLLOW = 'DELETE_FOLLOW'
export const DELETE_FOLLOW_RECEIVED = 'DELETE_FOLLOW_RECEIVED'
export const DELETE_FOLLOW_FAILED = 'DELETE_FOLLOW_FAILED'

export const CLEAR_DEL_FOLLOW = 'CLEAR_DEL_FOLLOW'

export const COUNT_FOLLOW = 'COUNT_FOLLOW'
export const COUNT_FOLLOW_RECEIVED = 'COUNT_FOLLOW_RECEIVED'
export const COUNT_FOLLOW_PERFIL_RECEIVED = 'COUNT_FOLLOW_PERFIL_RECEIVED'
export const COUNT_FOLLOW_FAILED = 'COUNT_FOLLOW_FAILED'

export const SET_COUNT_FOLLOW = 'SET_COUNT_FOLLOW'

export const FORO_POST_GET_PERFIL = 'FORO_POST_GET_PERFIL'
export const FORO_POST_GET_PERFIL_RECEIVED = 'FORO_POST_GET_PERFIL_RECEIVED'
export const FORO_POST_GET_PERFIL_FAILED = 'FORO_POST_GET_PERFIL_FAILED'

export const FORO_DELETE_POST = 'FORO_DELETE_POST'
export const FORO_DELETE_POST_RECEIVED = 'FORO_DELETE_POST_RECEIVED'
export const FORO_DELETE_POST_FAILED = 'FORO_DELETE_POST_FAILED'

export const CLEAR_DEL_POST = 'CLEAR_DEL_POST'

export const FORO_REPORT_POST = 'FORO_REPORT_POST'
export const FORO_REPORT_POST_RECEIVED = 'FORO_REPORT_POST_RECEIVED'
export const FORO_REPORT_POST_FAILED = 'FORO_REPORT_POST_FAILED'

export const CLEAR_REPORT_POST = 'CLEAR_REPORT_POST'

export const COMMENT_REPORT_POST = 'COMMENT_REPORT_POST'
export const COMMENT_REPORT_POST_RECEIVED = 'COMMENT_REPORT_POST_RECEIVED'
export const COMMENT_REPORT_POST_FAILED = 'COMMENT_REPORT_POST_FAILED'

export const CLEAR_REPORT_COMMENT = 'CLEAR_REPORT_POST'

export const SEARCH_POST = 'SEARCH_POST'
export const SEARCH_POST_RECEIVED = 'SEARCH_POST_RECEIVED'
export const SEARCH_POST_FAILED = 'SEARCH_POST_FAILED'

export const VALIDATE_FOLLOW = 'VALIDATE_FOLLOW';
export const VALIDATE_FOLLOW_RECEIVED = 'VALIDATE_FOLLOW_RECEIVED';
export const VALIDATE_FOLLOW_FAILED = 'VALIDATE_FOLLOW_FAILED';

export const FORO_POST_UPDATE = 'FORO_POST_UPDATE'
export const FORO_POST_UPDATE_RECEIVED = 'FORO_POST_UPDATE_RECEIVED'
export const FORO_POST_UPDATE_FAILED = 'FORO_POST_UPDATE_FAILED'

export const FORO_GET_CS = 'FORO_GET_CS';
export const FORO_GET_CS_RECEIVED = 'FORO_GET_CS_RECEIVED';
export const FORO_GET_CS_FAILED = 'FORO_GET_CS_FAILED';

export const UPDATE_POINT_COMMENT_GET = 'UPDATE_POINT_COMMENT_GET'
export const UPDATE_POINT_COMMENT_GET_RECEIVED = 'UPDATE_POINT_COMMENT_GET_RECEIVED'
export const UPDATE_POINT_COMMENT_GET_FAILED = 'UPDATE_POINT_COMMENT_GET_FAILED'

export const NOTIFICATION_GET = 'NOTIFICATION_GET'
export const NOTIFICATION_GET_RECEIVED = 'NOTIFICATION_GET_RECEIVED'
export const NOTIFICATION_GET_FAILED = 'NOTIFICATION_GET_FAILED'

export const UPDATE_STATUS_NOTI_ALL = 'UPDATE_STATUS_NOTI_ALL'
export const UPDATE_STATUS_NOTI_ALL_RECEIVED = 'UPDATE_STATUS_NOTI_ALL_RECEIVED'
export const UPDATE_STATUS_NOTI_ALL_FAILED = 'UPDATE_STATUS_NOTI_ALL_FAILED'

export const UPDATE_STATUS_NOTI = 'UPDATE_STATUS_NOTI'
export const UPDATE_STATUS_NOTI_RECEIVED = 'UPDATE_STATUS_NOTI_RECEIVED'
export const UPDATE_STATUS_NOTI_FAILED = 'UPDATE_STATUS_NOTI_FAILED'

/* ######################### FIN FORO ############################## */

/* ######################### NFT ################################# */

export const GET_NFT_BY_USER = 'GET_NFT_BY_USER'
export const GET_NFT_BY_USER_RECEIVED = 'GET_NFT_BY_USER_RECEIVED'
export const GET_NFT_BY_USER_FAILED = 'GET_NFT_BY_USER_FAILED'

export const GET_IMAGE_NFT_BY_STATUS = 'GET_IMAGE_NFT_BY_STATUS'
export const GET_IMAGE_NFT_BY_STATUS_RECEIVED = 'GET_IMAGE_NFT_BY_STATUS_RECEIVED'
export const GET_IMAGE_NFT_BY_STATUS_FAILED = 'GET_IMAGE_NFT_BY_STATUS_FAILED'

export const SAVE_SELECT_NFT = 'SAVE_SELECT_NFT'
export const SAVE_SELECT_NFT_RECEIVED = 'SAVE_SELECT_NFT_RECEIVED'
export const SAVE_SELECT_NFT_FAILED = 'SAVE_SELECT_NFT_FAILED'

export const GET_COLLECTIONS = 'GET_COLLECTIONS'
export const GET_COLLECTIONS_RECEIVED = 'GET_COLLECTIONS_RECEIVED'
export const GET_COLLECTIONS_FAILED = 'GET_COLLECTIONS_FAILED'

export const GET_NFT_BY_PERFIL = 'GET_NFT_BY_PERFIL'
export const GET_NFT_BY_PERFIL_RECEIVED = 'GET_NFT_BY_PERFIL_RECEIVED'
export const GET_NFT_BY_PERFIL_FAILED = 'GET_NFT_BY_PERFIL_FAILED'



/* ########################## FIN NFT ##################################### */